#!/usr/bin/env bash

### Debian based distros
###
# Install base packages
apt install -y vim \
    tmux \
    apt-transport-https \
    curl \
    htop

# Install nordvpn
wget https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb -P /home/matt/Downloads
apt-get install /home/matt/Downloads/*nordvpn-release_1.0.0_all.deb
apt-get update
apt-get -y install nordvpn

# Install spotify
snap install spotify

# Install wiregaurd
add-apt-repository ppa:wireguard/wireguard
apt install wireguard

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
